name: daily_health_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # CHANGED: This allows any Flutter 3.x version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  get: ^4.6.6
  google_sign_in: ^6.1.6   
  fl_chart: ^0.66.0        
  http: ^1.1.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true